# Example parameter file, see parameters_launch.py

# Format is namespace_name/node_name
my_camera/gscam_publisher:
  ros__parameters:
    gscam_config: 'udpsrc port=9201 ! application/x-rtp, media=video, encoding-name=H264 ! rtph264depay ! nvv4l2decoder ! nvvidconv flip-method=2 ! video/x-raw, format=BGRx ! videoconvert'
    preroll: False
    use_gst_timestamps: False
    frame_id: 'my_camera_frame'
